version: '3.1'
services:
  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewm_stats
      - POSTGRES_USER=ewm_stats
      - POSTGRES_PASSWORD=ewm_stats

  stats-server:
    #image: stats-server:0.0.1-SNAPSHOT
    build: stats/stats-server
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stats
      - POSTGRES_USER=ewm_stats
      - POSTGRES_PASSWORD=ewm_stats

  ewm-service:
    build: main-service
    container_name: main-service-container
    ports:
      - "8080:8080"

 # ewm-db:
 #   image: postgres:14-alpine
